services:
  postgres:
    image: 'postgres:18'
    container_name: postgres-order-service
    environment:
     POSTGRES_PASSWORD: postgres
     TZ: UTC
     PGTZ: UTC
    ports:
      - '5432:5432'
    volumes:
      - ./docker/postgres/init.sql:/docker-entrypoint-initdb.d/init.sql
